### ISSUE TITLE
Todo Präsi

### ISSUE THREAD

**Issue by darthkali** [fh-erfurt/MicroKino#10]
Danny:
- [x] Bild Projektübersicht anpassen: Kubernetes entfernen
- [x] Rechtschreibung und Grammatik
- [x] Pipeline Bild anpassen

Christian:
- [x] Hint in Readme das wir die Infrastruktur aufgeteilt haben
     - [x]  .env.remove... für windows einfügen
- [x] Reihenfolge der mappings beachten

Beide:
- [x] Kafka
